<a href="https://colab.research.google.com/github/kblank1125/kblank1125.github.io/blob/main/Scraper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
# // Web scraping: 
import requests
from bs4 import BeautifulSoup
# // OS. Sometimes need this for finding working directory:
import os

In [3]:
url='https://en.wikipedia.org/wiki/UEFA_Champions_League'

In [5]:
pd.read_html(url)
table=pd.read_html(url)

In [10]:
table[3]
df=table[3]

In [18]:
df.to_json('UEFA_winner.json')

In [22]:
df.to_csv('UEFA_winner.csv')

In [17]:
pd.read_json('UEFA_winner.json')

                        Club  ...                         Seasons runner-up
0                Real Madrid  ...                          1962, 1964, 1981
1                      Milan  ...                    1958, 1993, 1995, 2005
2              Bayern Munich  ...              1982, 1987, 1999, 2010, 2012
3                  Liverpool  ...                          1985, 2007, 2018
4                  Barcelona  ...                          1961, 1986, 1994
5                       Ajax  ...                                1969, 1996
6          Manchester United  ...                                2009, 2011
7                Inter Milan  ...                                1967, 1972
8                   Juventus  ...  1973, 1983, 1997, 1998, 2003, 2015, 2017
9                    Benfica  ...              1963, 1965, 1968, 1988, 1990
10                   Chelsea  ...                                      2008
11         Nottingham Forest  ...                                         —
12                     Porto  ...                                         —
13                    Celtic  ...                                      1970
14              Hamburger SV  ...                                      1980
15          Steaua București  ...                                      1989
16                 Marseille  ...                                      1991
17         Borussia Dortmund  ...                                      2013
18                 Feyenoord  ...                                         —
19               Aston Villa  ...                                         —
20             PSV Eindhoven  ...                                         —
21         Red Star Belgrade  ...                                         —
22           Atlético Madrid  ...                          1974, 2014, 2016
23                     Reims  ...                                1956, 1959
24                  Valencia  ...                                2000, 2001
25                Fiorentina  ...                                      1957
26       Eintracht Frankfurt  ...                                      1960
27                  Partizan  ...                                      1966
28             Panathinaikos  ...                                      1971
29              Leeds United  ...                                      1975
30             Saint-Étienne  ...                                      1976
31  Borussia Mönchengladbach  ...                                      1977
32               Club Brugge  ...                                      1978
33                  Malmö FF  ...                                      1979
34                      Roma  ...                                      1984
35                 Sampdoria  ...                                      1992
36          Bayer Leverkusen  ...                                      2002
37                    Monaco  ...                                      2004
38                   Arsenal  ...                                      2006
39         Tottenham Hotspur  ...                                      2019
40       Paris Saint-Germain  ...                                      2020
41           Manchester City  ...                                      2021

[42 rows x 5 columns]

In [24]:
pd.read_csv('UEFA_winner.csv')

    Unnamed: 0  ...                         Seasons runner-up
0            0  ...                          1962, 1964, 1981
1            1  ...                    1958, 1993, 1995, 2005
2            2  ...              1982, 1987, 1999, 2010, 2012
3            3  ...                          1985, 2007, 2018
4            4  ...                          1961, 1986, 1994
5            5  ...                                1969, 1996
6            6  ...                                2009, 2011
7            7  ...                                1967, 1972
8            8  ...  1973, 1983, 1997, 1998, 2003, 2015, 2017
9            9  ...              1963, 1965, 1968, 1988, 1990
10          10  ...                                      2008
11          11  ...                                         —
12          12  ...                                         —
13          13  ...                                      1970
14          14  ...                                      1980
15          15  ...                                      1989
16          16  ...                                      1991
17          17  ...                                      2013
18          18  ...                                         —
19          19  ...                                         —
20          20  ...                                         —
21          21  ...                                         —
22          22  ...                          1974, 2014, 2016
23          23  ...                                1956, 1959
24          24  ...                                2000, 2001
25          25  ...                                      1957
26          26  ...                                      1960
27          27  ...                                      1966
28          28  ...                                      1971
29          29  ...                                      1975
30          30  ...                                      1976
31          31  ...                                      1977
32          32  ...                                      1978
33          33  ...                                      1979
34          34  ...                                      1984
35          35  ...                                      1992
36          36  ...                                      2002
37          37  ...                                      2004
38          38  ...                                      2006
39          39  ...                                      2019
40          40  ...                                      2020
41          41  ...                                      2021

[42 rows x 6 columns]